/**
 * Static require() calls for bundled PNG sticker assets.
 *
 * Metro bundler requires these paths to remain static.
 */
export const STICKER_IMAGES = {
  cat_sleepy: require('../../../../assets/stickers/cat/sleepy.png'),
  cat_curious: require('../../../../assets/stickers/cat/curious.png'),
  cat_cozy: require('../../../../assets/stickers/cat/cozy.png'),
  cat_paw_print: require('../../../../assets/stickers/cat/paw-print.png'),
  cat_yarn_ball: require('../../../../assets/stickers/cat/yarn-ball.png'),
  cat_fish_treat: require('../../../../assets/stickers/cat/fish-treat.png'),
  school_notebook: require('../../../../assets/stickers/school/notebook.png'),
  school_pencil: require('../../../../assets/stickers/school/pencil.png'),
  school_backpack: require('../../../../assets/stickers/school/backpack.png'),
  school_eraser: require('../../../../assets/stickers/school/eraser.png'),
  school_ruler: require('../../../../assets/stickers/school/ruler.png'),
  school_crayon: require('../../../../assets/stickers/school/crayon.png'),
  summer_sun: require('../../../../assets/stickers/summer/sun.png'),
  summer_wave: require('../../../../assets/stickers/summer/wave.png'),
  summer_ice_cream: require('../../../../assets/stickers/summer/ice-cream.png'),
  summer_sunglasses: require('../../../../assets/stickers/summer/sunglasses.png'),
  summer_beach_ball: require('../../../../assets/stickers/summer/beach-ball.png'),
  summer_popsicle: require('../../../../assets/stickers/summer/popsicle.png'),
  winter_snowflake: require('../../../../assets/stickers/winter/snowflake.png'),
  winter_scarf: require('../../../../assets/stickers/winter/scarf.png'),
  winter_snow_globe: require('../../../../assets/stickers/winter/snow-globe.png'),
  winter_mitten: require('../../../../assets/stickers/winter/mitten.png'),
  winter_hot_cocoa: require('../../../../assets/stickers/winter/hot-cocoa.png'),
  winter_beanie: require('../../../../assets/stickers/winter/beanie.png'),
  spring_blossom: require('../../../../assets/stickers/spring/blossom.png'),
  spring_tulip: require('../../../../assets/stickers/spring/tulip.png'),
  spring_daisy: require('../../../../assets/stickers/spring/daisy.png'),
  spring_bee: require('../../../../assets/stickers/spring/bee.png'),
  spring_rain_boot: require('../../../../assets/stickers/spring/rain-boot.png'),
  spring_butterfly: require('../../../../assets/stickers/spring/butterfly.png'),
  fall_leaf: require('../../../../assets/stickers/fall/leaf.png'),
  fall_pumpkin: require('../../../../assets/stickers/fall/pumpkin.png'),
  fall_acorn: require('../../../../assets/stickers/fall/acorn.png'),
  fall_apple: require('../../../../assets/stickers/fall/apple.png'),
  fall_mushroom: require('../../../../assets/stickers/fall/mushroom.png'),
  fall_pie_slice: require('../../../../assets/stickers/fall/pie-slice.png'),
  scribble_heart: require('../../../../assets/stickers/scribble/heart.png'),
  scribble_starburst: require('../../../../assets/stickers/scribble/starburst.png'),
  scribble_thought: require('../../../../assets/stickers/scribble/thought.png'),
  scribble_swoosh: require('../../../../assets/stickers/scribble/swoosh.png'),
  scribble_flower: require('../../../../assets/stickers/scribble/flower.png'),
  scribble_tape_note: require('../../../../assets/stickers/scribble/tape-note.png'),
  frames_taped_paper: require('../../../../assets/stickers/frames/taped-paper.png'),
  frames_torn_paper: require('../../../../assets/stickers/frames/torn-paper.png'),
  frames_notebook_edge: require('../../../../assets/stickers/frames/notebook-edge.png'),
  frames_punched_edge: require('../../../../assets/stickers/frames/punched-edge.png'),
  frames_soft_scallop: require('../../../../assets/stickers/frames/soft-scallop.png'),
  frames_corner_tabs: require('../../../../assets/stickers/frames/corner-tabs.png'),
} as const;

export type StickerImageKey = keyof typeof STICKER_IMAGES;
